### ISSUE TITLE
Feature request: allow buttons to run custom scripts

### ISSUE THREAD

**Issue by kencodes** [Snille/MMM-Modulebar#1]
Hello,

I like the interface you developed and I want to use it to run python scripts I've written that control things around my house. For example, I am running MM on a Raspberry Pi and 7" touchscreen on my bedside table and I would like a Modulebar button with a custom name and icon that toggles the lights in my room. How can I adapt your work to accomplish this, or does your module already support this?

Thanks for any help you can provide

**Comment by Snille** [comment]
Hi! This was a long time ago. :) But I don't think it can run scripts by it self. It's purpurs is to show and hide other modules on the mirror (that may run scripts... :)...

**Comment by kencodes** [comment]
Understood. Thanks anyway :)

**Comment by Snille** [comment]
No problem. :)
