### ISSUE TITLE
Force Modulebar To Top Layer?

### ISSUE THREAD

**Issue by Dresch360** [Snille/MMM-Modulebar#11]
I'm having an issue trying to use MMM-Modulebar with MMM-AmbientBrightnessDetection. After MMM-AmbientBrightnessDetection executes, the Modulebar buttons are no longer clickable/active. Is there a way to force MMM-Modulebar to the top layer? For example, the MMM-HideAll button always remains in the top layer, but I can't seem to figure it out for MMM-Modulebar. 
Any help would be greatly appreciate and thanks again for you awesome module!

**Comment by Dresch360** [comment]
I figured it out - In MMM-Modulebar.css, change z-index to 2.

**Comment by Snille** [comment]
Oh, good that you fixed it! :) Actually you don't need to use the MMM-HideAll module any longer if you use the MMM-Modulebar. It has that function built in now. You can set a button to do the same function. :)
