### ISSUE TITLE
Feature Request: navigate to another url

### ISSUE THREAD

**Issue by clyra** [Snille/MMM-Modulebar#12]
Hi,

I'm wondering if it would be possible to configure a button to navigate to another url? I'm using  a docker server only MM and opening it on a tablet. I would like to alternate between my home assistant dashboard and MM. Going from Home Assistant to MM is easy, but the other way is not. Since the browser is always on fullscreen mode, having a button on screen to navigate to another URL would be very nice.

thanks!

**Comment by Snille** [comment]
Hi, I understand what you want to do but it's not really the purpose of this module. It's made to hide and show other modules. Maybe there is another module out there that can do it? :)
