### ISSUE TITLE
How to determine the IDNUM parameter

### ISSUE THREAD

**Issue by mmycjguo** [Snille/MMM-Modulebar#14]
I used multiple modules of the same, I only want to control one of them, how to determine the IDNUM parameter

			module: "MMM-Modulebar",
			position: "right_bottom", // This can be any of the regions.
			header: "", // Optional
			classes: "default everyone", // Optional
			config: {
							// See 'Configuration options' for more information.
				       direction: "row-reverse",
							buttons: {
					// A number (uniqe for each button).
					"1": {
					  // A button with only text
					  module: "all",
					  symbol: "fas fa-power-off",
					},
					"2": {
					  
					  module: "MMM-iFrame",
					  idnum: ???,
					  symbol: "far fa-calendar-alt",

					},

**Comment by Snille** [comment]
Open the "mirror" in Chrome, press F12 (debug mode) and expand the body-tag down to the module you are looking for. The ID number is displayed in the "id-string" of the module, see picture.... :)
![image](https://user-images.githubusercontent.com/1011699/126765248-7743f95f-e743-4a1c-8322-700f7ab291d2.png)

PS: The number of the module will change every time you add/remove a module "above" (in the config). All modules after the change vill then get new numbers...

**Comment by mmycjguo** [comment]
It's ok now,thank you very much

Erik Pettersson ***@***.***> 于2021年7月23日周五 下午5:47写道：
