### ISSUE TITLE
Modulebar only one Module is working

### ISSUE THREAD

**Issue by IchPeter** [Snille/MMM-Modulebar#2]
Hello maybe anybody can help me, I have installed MMM-Modulebar and I love it but only one Module ist working, iFrame only. When I try two or tree modules only one is correct working. 
{
        		module: "MMM-Modulebar",
       			position: "top_bar", // This can be any of the regions.
			//header: "Module", // Optional
        		classes: "default everyone", // Optional
        		config: {
        			buttons: {
   				 	
						"1": {
      						module: "MMM-iFrame",
      						text: "SmartHome",
						symbol: "cloud",
      					},
      					
						"2": {
      						module: "MMM-EARTH",
      						text: "Erde",
						symbol: "star-o",
      					},
					
						"3": {
      						module: "MMM-Mail",
      						text: "E-Mail",
						symbol: "star-o",
      					},
      				}
           			
       			}Heve anybody an idea or can help me and explain the settings??

Many thanks

**Comment by Snille** [comment]
Hi! Hmm.. I cant see anything wrong. I should work. Does the modules show at all? When not activated by the Modulebar?

**Comment by IchPeter** [comment]
Many thanks yes the Module are shown in die Mirror. With Remote Control I can hide or show the Modules. All are Standard shown. Thanks Peter     	    	
    	Danke 
Peter StutzVor der Kipp 1266649 Oberthal       



On Wed, Apr 15, 2020 at 7:48 AM +0200, "Erik Pettersson" <notifications@github.com> wrote:















Hi! Hmm.. I cant see anything wrong. I should work. Does the modules show at all? When not activated by the Modulebar?

**Comment by IchPeter** [comment]
Hello do you have any ideas Modulebar are not working, oonly one Module, number 1, 2 and 3 still not working. I checked everything and can't find problems in my config.
Thanky
Peter

**Comment by Snille** [comment]
As I wrote before, I can't see anything wrong. It's all working for me.
Here is a video with the same things: https://youtu.be/dQJYZjNWZ_0
Here is the config I used for the video: 
```javascript
// Test here!
		{
			module: 'MMM-iFrame',
			position: 'middle_center',	// This can be any of the regions.
			config: {
				// See 'Configuration options' for more information.
				url: ["https://ismyinternetworking.com"],  // as many URLs you want or you can just ["ENTER IN URL"] if single URL.
				updateInterval: 0.5 * 60 * 1000, // rotate URLs every 30 seconds
				width: "1280", // width of iframe
				height: "720", // height of iframe
				frameWidth: "400" // width of embedded iframe, height is beeing calculated by aspect ratio of iframe
			}
		},
		{
			module: "MMM-EARTH",
			position: "middle_center",
			config: {
				mode: "Natural",
				rotateInterval: 15000,
				MaxWidth: "50%",
				MaxHeight: "50%",
			}
		},
		{
			module: 'MMM-Mail',
			position: 'bottom_left',
			header: 'Email',
			config:{
				user: 'johndoe@gmail.com',
				pass: 'xxx',
				host: 'imap.gmail.com',
				port: 993,
				numberOfEmails: 5,
				fade: true,
				subjectlength: 50
			},
		},
		{
			module: "MMM-Modulebar",
			position: "top_bar", // This can be any of the regions.
			//header: "Module", // Optional
			classes: "default everyone", // Optional
			config: {
				buttons: {
					"1": {
						module: "MMM-iFrame",
						text: "SmartHome",
						symbol: "cloud",
					},
					"2": {
						module: "MMM-EARTH",
						text: "Erde",
						symbol: "star-o",
					},
					"3": {
						module: "MMM-Mail",
						text: "E-Mail",
						symbol: "star-o",
					}
				}
			}
		},
// End Here!
```

**Comment by IchPeter** [comment]
Hey Erik, Your config is running many thanks but I cant't found any problems in my config all modules are running without your modulebar. Only one module is running it's iFrame. Maybe there is an mistake with other modules in my own config. If you want I can send you my complete config?? 
Have nice time Peter

**Comment by Snille** [comment]
Hi again, please ask in the forum instead, there is probably someone who can help: https://forum.magicmirror.builders/

**Comment by IchPeter** [comment]
Yes I will do it many thanks fit helping. 
    	
    	

    	Danke 
Peter StutzVor der Kipp 1266649 Oberthal 
    
  




On Sun, Apr 19, 2020 at 10:35 PM +0200, "Erik Pettersson" <notifications@github.com> wrote:















Hi again, please ask in the forum instead, there is probably someone who can help: https://forum.magicmirror.builders/
