### ISSUE TITLE
Buttons not clickable

### ISSUE THREAD

**Issue by Dresch360** [Snille/MMM-Modulebar#3]
Thank you for creating an awesome module. The module is loaded and working and buttons are showing on the MM display, but are not clickable. Any help would be greatly appreciated!

**Comment by Snille** [comment]
Hi, I actually had the same problem on a new install just the other week, It was due to another faulty module (don't remember what module it was now). Check the logs, see if you can find something that's not behaving.

**Comment by Dresch360** [comment]
Thanks for your quick response!

**Comment by Dresch360** [comment]
From what I can tell, the  MMM-Modulebar stop working after 10 modules are loaded/displayed.

**Comment by Dresch360** [comment]
Separately, do you know how I can start a module "hidden" and then click a button to unhide after MM loads?

**Comment by Snille** [comment]
Yes,  you can just set a "classes" that is not used... I do it for all my "Motion Eye" modules, like this: `classes: "None"`.
However, the module is still "active" so if it "breaking" things it will still do that, even if it's hidden.
You can also (I think) disable a module with `disabled: true` at the start of the modules config. But I'm not sure if it still loads the code anyway.

**Comment by Dresch360** [comment]
Thanks so much! I think I've figured it out. If there are a more than 10 modules in the MM display, the modules that are defined as buttons need to immediately proceed the  MMM-Modulebar modules, otherwise, it appears to that the MM display runs out of memory - even for modules that are  set to disabled: true.  It works now after placing the modules defined in MMM-Modulebar immediately after the module.

**Comment by Snille** [comment]
All good then, I'll close the case. :)
