### ISSUE TITLE
Invisible main button :-)

### ISSUE THREAD

**Issue by KamiSchami** [Snille/MMM-Modulebar#5]
Hello, great module. Would it be possible that the main button disappears after a while or is only slightly visible?

Greetings from Germany

**Comment by Snille** [comment]
Hi, you can do this with some CSS-magic and two instances of the Module bar. Just make specific CSS for the "main" one (containing the "first" / "last" button), that hides itself when you activate the second one. See the other "[issue](https://github.com/Snille/MMM-Modulebar/issues/4)" for more information how to set up two module bars... :)

**Comment by KamiSchami** [comment]
Hi, ok i will look at it. Thank you

**Comment by Snille** [comment]
No problem. I'll close this now. :)
