### ISSUE TITLE
Initially hidden

### ISSUE THREAD

**Issue by MystaraTheGreat** [Snille/MMM-Modulebar#6]
Is it possible to have a module initially hidden and then have the button make it appear?
If so, how is this achieved?

Thanks

**Comment by Snille** [comment]
Hi @Mystara2002 I think you need the module [MMM-ProfileSwitcher](https://github.com/tosti007/MMM-ProfileSwitcher) (to be able to use profiles) and then you have to use two Modulebars, one "hidden" by default (with all the buttons) and one with only one button. Check out issue #4 for a config example of this.
