### ISSUE TITLE
Maybe move the MMM-HideAll module into this module?

### ISSUE THREAD

**Issue by asionyang** [Snille/MMM-Modulebar#7]
Hi,really like your work, this module helps a lot. But when the amount of modules becomes a lot , I realise this module can't  hide or show all modules using just one button. And then I found that this HideAll module is also your work, so why not combine these two together?  I quite looked forward to this new version coming.

**Comment by Snille** [comment]
Hi @asionyang, actually the MMM-HideAll is not my module. :) I have just forked it to be able to add more configuration options to it. I'm not sure I can combine the two, they don't work the same. But it's a great Idea! Maybe some day when I have more time I'll see if it can be done. Or if you can, try it, and send a PR. :)

**Comment by asionyang** [comment]
> Hi @asionyang, actually the MMM-HideAll is not my module. :) I have just forked it to be able to add more configuration options to it. I'm not sure I can combine the two, they don't work the same. But it's a great Idea! Maybe some day when I have more time I'll see if it can be done. Or if you can, try it, and send a PR. :)

Thanks for the reply @Snille. I'd really like to try, but I'm definitely new to ALL THIS whole code-programing thing, I've tried all I can to improve some modules since many of those seems deprecated. Actually this is the first issue i've ever write. But I get it when you say you need more time. And I'm glad if I enlighten you a little bit.

**Comment by asionyang** [comment]
Hi @Snille , I've decided to give it a try！And I think I had it done . So I send a PR but I don't know if I send it the right way, cause I'm pretty new to this. And I'm also not quite confident with my code, which works fine on my docker though (just for now). so could you please give it a test ? Thanks a lot!

**Comment by Snille** [comment]
Hi @asionyang, thank you for trying! You did it correct! However the PR has to be denied. It's not usable for everybody. :) Read the response (explanation) in the PR. However you can of course you it yourself if it works for you. :)

**Comment by Snille** [comment]
Thank you for taking the time! It's now working and I had some time to add a bit more functionality. :)
